;;; autoload/bindings-gallium.el -*- lexical-binding: t; -*-

;;;###autoload
(defconst meow-cheatsheet-layout-gallium
  '((<TLDE> "`"	"~")
    (<AE01> "1"	"!")
    (<AE02> "2"	"@")
    (<AE03> "3"	"#")
    (<AE04> "4"	"$")
    (<AE05> "5"	"%")
    (<AE06> "6"	"^")
    (<AE07> "7"	"&")
    (<AE08> "8"	"*")
    (<AE09> "9"	"(")
    (<AE10> "0"	")")
    (<AE11> "-"	"_")
    (<AE12> "="	"+")
    (<AD01> "b"	"B")
    (<AD02> "l"	"L")
    (<AD03> "d"	"D")
    (<AD04> "c"	"C")
    (<AD05> "v"	"V")
    (<AD06> "j"	"J")
    (<AD07> "f"	"F")
    (<AD08> "o"	"O")
    (<AD09> "u"	"U")
    (<AD10> ";"	":")
    (<AD11> "["	"{")
    (<AD12> "]"	"}")
    (<AC01> "n"	"N")
    (<AC02> "r"	"R")
    (<AC03> "t"	"T")
    (<AC04> "s"	"S")
    (<AC05> "g"	"G")
    (<AC06> "y"	"Y")
    (<AC07> "h"	"H")
    (<AC08> "a"	"A")
    (<AC09> "e"	"E")
    (<AC10> "i"	"I")
    (<AC11> ","	"<")
    (<AB01> "x"	"X")
    (<AB02> "q"	"Q")
    (<AB03> "m"	"M")
    (<AB04> "w"	"W")
    (<AB05> "z"	"Z")
    (<AB06> "k"	"K")
    (<AB07> "p"	"P")
    (<AB08> "'"	"\"")
    (<AB09> "/"	"?")
    (<AB10> "."	">")
    (<BKSL> "\\" "|"))
  "Meow cheatsheet layout for Gallium (column-staggered).")

;;;###autoload
(defun +meow--setup-gallium ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-gallium)

  (meow-motion-overwrite-define-key
   ;; Use next-line/previous-line (not meow-next/meow-prev) because the latter
   ;; deactivate the region, which is unhelpful in motion state.
   '("a" . next-line)
   '("e" . previous-line))

  (meow-leader-define-key
   ;; SPC a/e run the original commands shadowed by motion-state bindings
   ;; (because we set `meow-motion-remap-prefix' to "C-")
   '("a" . "C-a")
   '("e" . "C-e")
   ;; Use SPC (0-9) for digit arguments.
   '("1" . meow-digit-argument)
   '("2" . meow-digit-argument)
   '("3" . meow-digit-argument)
   '("4" . meow-digit-argument)
   '("5" . meow-digit-argument)
   '("6" . meow-digit-argument)
   '("7" . meow-digit-argument)
   '("8" . meow-digit-argument)
   '("9" . meow-digit-argument)
   '("0" . meow-digit-argument)
   '("/" . meow-keypad-describe-key)
   '("?" . meow-cheatsheet))

  (meow-normal-define-key
   ;; number row
   '("{" . backward-paragraph)
   '("(" . meow-page-up)
   '(")" . meow-page-down)
   '("}" . forward-paragraph)

   ;; top row
   '("=" . meow-swap-grab)
   '("b" . meow-join)
   '("l" . meow-line)
   '("L" . meow-goto-line)
   '("d" . meow-kill)
   '("c" . meow-save)
   '("v" . meow-visit)
   '("z" . meow-pop-selection)
   '("Z" . meow-pop-all-selection)
   '("f" . meow-find)
   '("F" . pop-to-mark-command)
   '("o" . meow-block)
   '("O" . meow-to-block)
   '("u" . undo-only)
   '("U" . undo-redo)
   '(";" . meow-reverse)
   '(":" . execute-extended-command)
   '("_" . avy-goto-char-timer)
   '("-" . negative-argument)

   ;; home row
   '("n" . meow-till)
   '("r" . meow-change)
   '("R" . meow-replace)
   '("t" . meow-insert)
   '("T" . meow-open-above)
   '("s" . meow-append)
   '("S" . meow-open-below)
   '("g" . meow-cancel-selection)
   '("G" . meow-grab)
   '("y" . meow-beginning-of-thing)
   '("h" . meow-left)
   '("H" . meow-left-expand)
   '("a" . meow-next)
   '("A" . meow-next-expand)
   '("e" . meow-prev)
   '("E" . meow-prev-expand)
   '("i" . meow-right)
   '("I" . meow-right-expand)
   '("," . meow-end-of-thing)

   ;; bottom row
   '("q" . quit-window)
   '("x" . meow-delete)
   '("X" . meow-backward-delete)
   '("m" . meow-mark-word)
   '("M" . meow-mark-symbol)
   '("w" . meow-expand)
   '("j" . meow-search)
   '("k" . meow-inner-of-thing)
   '("K" . meow-bounds-of-thing)
   '("p" . meow-yank)
   '("P" . meow-yank-pop)
   '("'" . meow-back-word)
   '("\"" . meow-back-symbol)
   '("/" . meow-next-word)
   '("?" . meow-next-symbol)
   '("." . repeat)

   ;; other
   '("0" . meow-expand-0)
   '("1" . meow-expand-1)
   '("2" . meow-expand-2)
   '("3" . meow-expand-3)
   '("4" . meow-expand-4)
   '("5" . meow-expand-5)
   '("6" . meow-expand-6)
   '("7" . meow-expand-7)
   '("8" . meow-expand-8)
   '("9" . meow-expand-9)
   '("^" . pop-global-mark)
   '("$" . save-buffer)
   '("#" . comment-line)
   '("*" . magit-status))
  )
